import type { InstrumentConfig } from '../types/instrument';

export const synthesizer: InstrumentConfig = {
  id: 'synthesizer',
  name: 'Synthesizer',
  type: 'tonal',
  icon: 'synth',
  keyMappings: {
    a: { key: 'a', label: 'C3', pitch: 48, frequency: 130.81, oscillatorType: 'square' },
    s: { key: 's', label: 'D3', pitch: 50, frequency: 146.83, oscillatorType: 'square' },
    d: { key: 'd', label: 'E3', pitch: 52, frequency: 164.81, oscillatorType: 'square' },
    f: { key: 'f', label: 'F3', pitch: 53, frequency: 174.61, oscillatorType: 'square' },
    g: { key: 'g', label: 'G3', pitch: 55, frequency: 196.0, oscillatorType: 'square' },
    h: { key: 'h', label: 'A3', pitch: 57, frequency: 220.0, oscillatorType: 'square' },
    j: { key: 'j', label: 'B3', pitch: 59, frequency: 246.94, oscillatorType: 'square' },
    k: { key: 'k', label: 'C4', pitch: 60, frequency: 261.63, oscillatorType: 'square' },
    l: { key: 'l', label: 'D4', pitch: 62, frequency: 293.66, oscillatorType: 'square' },
    ';': { key: ';', label: 'E4', pitch: 64, frequency: 329.63, oscillatorType: 'square' },
    q: { key: 'q', label: 'C4', pitch: 60, frequency: 261.63, oscillatorType: 'triangle' },
    w: { key: 'w', label: 'D4', pitch: 62, frequency: 293.66, oscillatorType: 'triangle' },
    e: { key: 'e', label: 'E4', pitch: 64, frequency: 329.63, oscillatorType: 'triangle' },
    r: { key: 'r', label: 'F4', pitch: 65, frequency: 349.23, oscillatorType: 'triangle' },
    t: { key: 't', label: 'G4', pitch: 67, frequency: 392.0, oscillatorType: 'triangle' },
    y: { key: 'y', label: 'A4', pitch: 69, frequency: 440.0, oscillatorType: 'triangle' },
    u: { key: 'u', label: 'B4', pitch: 71, frequency: 493.88, oscillatorType: 'triangle' },
    i: { key: 'i', label: 'C5', pitch: 72, frequency: 523.25, oscillatorType: 'triangle' },
    o: { key: 'o', label: 'D5', pitch: 74, frequency: 587.33, oscillatorType: 'triangle' },
    p: { key: 'p', label: 'E5', pitch: 76, frequency: 659.25, oscillatorType: 'triangle' },
  },
};
